name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang-version:
          - '21.0'
          - '20.3'
          - '19.3'
          - '18.3'

    container:
      image: erlang:${{ matrix.erlang-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: ./rebar3 compile
    - name: Run tests
      run: ./rebar3 do eunit, ct
    - name: Run xref
      run: ./rebar3 xref
    - name: Run dialyzer
      run: ./rebar3 dialyzer
    - name: Run edoc
      run: ./rebar3 as dev edoc
